services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=desafio_sicredi
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
