CREATE TABLE IF NOT EXISTS pautas (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descicao TEXT NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT UK_titulo UNIQUE (titulo)
)